r"""summary.csv -> paper/tables/*.tex (booktabs; \input{} into the manuscript,
so no number is ever typed by hand).

Usage: python -m analysis.make_tables --config configs/default.yaml
"""
from __future__ import annotations

import argparse
from pathlib import Path

import numpy as np
import pandas as pd

from analysis.figure_style import MODEL_LABEL, MODEL_ORDER, TIER_LABEL
from src.utils.common import load_config


def fmt(mean, std, best=False, second=False, digits=3):
    if pd.isna(mean):
        return "--"
    s = f"{mean:.{digits}f}" + (f" {{\\small$\\pm${std:.{digits}f}}}"
                                if not pd.isna(std) else "")
    if best:
        return f"\\textbf{{{s}}}"
    if second:
        return f"\\underline{{{s}}}"
    return s


def main_benchmark_table(summ, wil, out):
    sub = summ[(summ.stage == "benchmark") & (summ.split == "test")
               & (summ.subgroup == "ALL") & (summ.dataset == "brfss2022")]
    tiers = [t for t in ["T0", "T1", "T1_portable", "T2"]
             if t in sub.tier.unique()]
    lines = [
        "% AUTO-GENERATED by analysis/make_tables.py — do not edit by hand",
        "\\begin{tabular}{l" + "cc" * len(tiers) + "}", "\\toprule",
        "& " + " & ".join(f"\\multicolumn{{2}}{{c}}{{{TIER_LABEL[t]}}}"
                          for t in tiers) + " \\\\",
        "Model " + "".join(f"& AUROC & AUPRC " for _ in tiers) + "\\\\",
        "\\midrule"]
    def cell(t, m, metric):
        r = sub[(sub.tier == t) & (sub.model == m) & (sub.metric == metric)]
        return (r["mean"].iloc[0], r["std"].iloc[0]) if len(r) else (np.nan,
                                                                     np.nan)
    for m in [m for m in MODEL_ORDER if m in sub.model.unique()]:
        cells = []
        for t in tiers:
            for metric in ("auroc", "auprc"):
                mean, std = cell(t, m, metric)
                col = sub[(sub.tier == t) & (sub.metric == metric)]
                ranked = col.sort_values("mean",
                                         ascending=False).model.tolist()
                cells.append(fmt(mean, std, best=(ranked[:1] == [m]),
                                 second=(len(ranked) > 1
                                         and ranked[1] == m)))
        sig = ""
        if wil is not None and len(wil):
            w = wil[(wil.tier.isin(tiers)) & (wil.model == m)
                    & (wil.metric == "auroc")
                    & (wil.wilcoxon_p_holm < 0.05)]
            if len(w):
                sig = "$^{\\dagger}$"
        lines.append(f"{MODEL_LABEL.get(m, m)}{sig} & "
                     + " & ".join(cells) + " \\\\")
    lines += ["\\bottomrule", "\\end{tabular}",
              "% dagger: Holm-adjusted Wilcoxon p<0.05 vs EBM "
              "(across-seed, test AUROC)"]
    (out / "tab_main_benchmark.tex").write_text("\n".join(lines))


def temporal_table(summ, out):
    sub = summ[(summ.stage == "temporal") & (summ.subgroup == "ALL")]
    if not len(sub):
        return
    piv = sub[sub.metric.isin(["auroc", "auprc", "cal_slope",
                               "screening_sensitivity",
                               "screening_specificity"])].pivot_table(
        index="model", columns="metric", values="mean")
    lines = ["% AUTO-GENERATED", "\\begin{tabular}{lccccc}", "\\toprule",
             "Model & AUROC & AUPRC & Cal. slope & Sens.@screen & "
             "Spec.@screen \\\\", "\\midrule"]
    for m in [m for m in MODEL_ORDER if m in piv.index]:
        r = piv.loc[m]
        lines.append(f"{MODEL_LABEL.get(m, m)} & "
                     + " & ".join(f"{r.get(c, np.nan):.3f}"
                                  if not pd.isna(r.get(c, np.nan)) else "--"
                                  for c in ["auroc", "auprc", "cal_slope",
                                            "screening_sensitivity",
                                            "screening_specificity"])
                     + " \\\\")
    lines += ["\\bottomrule", "\\end{tabular}"]
    (out / "tab_temporal_2023.tex").write_text("\n".join(lines))


def fairness_table(cfg, out):
    rows = []
    fdir = Path(cfg["results_dir"]) / "fairness"
    for f in fdir.glob("*/*/*/seed*/frontier.csv"):
        df = pd.read_csv(f)
        parts = f.parts
        df["model"], df["seed"] = parts[-3], parts[-2]
        rows.append(df)
    if not rows:
        return
    fr = pd.concat(rows)
    agg = fr.groupby(["model", "arm"]).agg(
        sens=("sensitivity", "mean"), sens_sd=("sensitivity", "std"),
        spec=("specificity", "mean"), spec_sd=("specificity", "std"),
        gap=("tpr_gap", "mean"), gap_sd=("tpr_gap", "std")).reset_index()
    arm_order = ["baseline", "group_thr", "reweigh", "repair_half",
                 "repair_zero", "repair_eq"]
    lines = ["% AUTO-GENERATED", "\\begin{tabular}{llccc}", "\\toprule",
             "Model & Arm & Sensitivity & Specificity & "
             "TPR gap (Sex) \\\\", "\\midrule"]
    for m in agg.model.unique():
        for arm in arm_order:
            r = agg[(agg.model == m) & (agg.arm == arm)]
            if not len(r):
                continue
            r = r.iloc[0]
            lines.append(
                f"{MODEL_LABEL.get(m, m)} & {arm.replace('_', ' ')} & "
                f"{fmt(r.sens, r.sens_sd)} & {fmt(r.spec, r.spec_sd)} & "
                f"{fmt(r.gap, r.gap_sd)} \\\\")
        lines.append("\\midrule")
    lines[-1] = "\\bottomrule"
    lines.append("\\end{tabular}")
    (out / "tab_fairness_arms.tex").write_text("\n".join(lines))


def conformal_table(cfg, out):
    rows = []
    cdir = Path(cfg["results_dir"]) / "conformal"
    for f in cdir.glob("*/*/*/seed*/coverage_alpha*.csv"):
        df = pd.read_csv(f)
        df["model"], df["seed"] = f.parts[-3], f.parts[-2]
        rows.append(df)
    if not rows:
        return
    cv = pd.concat(rows)
    cv = cv[cv.group_var.isin(["ALL", "Sex", "AgeBand"])]
    agg = cv.groupby(["model", "method", "group_var", "group"]).agg(
        cov=("coverage", "mean"), cov_sd=("coverage", "std"),
        size=("avg_set_size", "mean"),
        defer=("deferral_rate", "mean")).reset_index()
    lines = ["% AUTO-GENERATED", "\\begin{tabular}{lllccc}", "\\toprule",
             "Model & Method & Group & Coverage & Avg. set size & "
             "Deferral \\\\", "\\midrule"]
    for (m, meth), g in agg.groupby(["model", "method"]):
        for r in g.itertuples():
            lines.append(f"{MODEL_LABEL.get(m, m)} & "
                         f"{meth.replace('_', ' ')} & "
                         f"{r.group_var}={r.group} & "
                         f"{fmt(r.cov, r.cov_sd)} & {r.size:.2f} & "
                         f"{r.defer:.3f} \\\\")
    lines += ["\\bottomrule", "\\end{tabular}"]
    (out / "tab_conformal.tex").write_text("\n".join(lines))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--config", default="configs/default.yaml")
    a = ap.parse_args()
    cfg = load_config(a.config)
    rdir = Path(cfg["results_dir"])
    out = Path("paper/tables")
    out.mkdir(parents=True, exist_ok=True)
    summ = pd.read_csv(rdir / "summary.csv")
    wil = None
    wpath = rdir / "wilcoxon.csv"
    if wpath.exists():
        try:
            wil = pd.read_csv(wpath)
        except pd.errors.EmptyDataError:
            wil = None
    main_benchmark_table(summ, wil, out)
    temporal_table(summ, out)
    fairness_table(cfg, out)
    conformal_table(cfg, out)
    print("[tables] written to paper/tables/")


if __name__ == "__main__":
    main()
